export enum Levels {
    BEGINNER = "BEGINNER",
    BASIC = "BASIC",
    INTERMEDIATE = "INTERMEDIATE",
    UPPER_INTERMEDIATE = "UPPER_INTERMEDIATE",
    ADVANCED = "ADVANCED",
    EXPERT = "EXPERT"
}
